# Generated by Django 3.0.5 on 2020-04-22 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('event_title', models.CharField(max_length=128)),
                ('location', models.CharField(max_length=128)),
                ('start_dt', models.DateTimeField()),
                ('message', models.CharField(max_length=5000)),
                ('invitee_emails', models.CharField(max_length=5000)),
            ],
        ),
    ]
