# Generated by Django 3.0.5 on 2020-04-30 05:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=128, verbose_name='Name of Event:')),
                ('location', models.CharField(max_length=256, verbose_name='Event Location:')),
                ('start_dt', models.DateTimeField(help_text='Please select the date and time (displayed in 24-hour format) to START your event.', verbose_name='Start Date:')),
                ('end_dt', models.DateTimeField(help_text='Please select the date and time (displayed in 24-hour format) to END your event.', verbose_name='End Date:')),
                ('message', models.CharField(help_text='Please enter a message you would like to tell your guests.', max_length=5000, verbose_name='Message:')),
                ('invitee_emails', models.CharField(help_text="Please use ;'s' to seperate emails addresses.", max_length=5000, verbose_name='Invitee(s) Email Address:')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('create_event_user', models.ForeignKey(default=99999999, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
