# Generated by Django 3.0.5 on 2020-04-26 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200424_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_dt',
            field=models.DateTimeField(),
        ),
    ]
