# Generated by Django 3.0.5 on 2020-04-29 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200426_0524'),
        ('core', '0003_auto_20200426_0211'),
    ]

    operations = [
    ]
